import {
  BookMarked,
  Cpu,
  Network,
  Database,
  BrainCircuit,
  Lock,
  ImageIcon,
  Wifi,
  Zap,
  Cloud,
  LineChart,
  Eye,
  Fingerprint,
  FileText,
  User,
  Calendar,
} from "lucide-react"

// Faculty data
export const facultyData = [
  {
    id: 1,
    name: "Dr. Amalan Joseph Antony A",
    position: "Assistant Professor",
    image: "/placeholder.svg?height=300&width=300",
    interests: ["Cryptography", "Data Structures and Algorithms", "Theory of Computation"],
    email: "amalan@iiitdm.ac.in",
    phone: "+91-XXXXXXXXXX",
    office: "Faculty Block, Room 101",
    education: [
      { degree: "Ph.D", university: "IIT Madras", year: "2018" },
      { degree: "M.Tech", university: "NIT Trichy", year: "2012" },
      { degree: "B.Tech", university: "Anna University", year: "2010" },
    ],
    publications: 12,
    projects: 4,
    students: 5,
    courses: ["Discrete Mathematics", "Algorithm Design", "Cryptography"],
    socialLinks: {
      linkedin: "https://linkedin.com/in/",
      github: "https://github.com/",
      website: "https://example.com/",
    },
    interestIcons: [
      { icon: "Lock", component: Lock },
      { icon: "FileText", component: FileText },
      { icon: "BookMarked", component: BookMarked },
    ],
  },
  {
    id: 2,
    name: "Dr. Bhukya Krishna Priya",
    position: "Assistant Professor",
    image: "/placeholder.svg?height=300&width=300",
    interests: [
      "Computer Architecture",
      "Memory Technologies",
      "Machine Learning",
      "Image Processing",
      "Vehicular Networks",
    ],
    email: "krishnapriya@iiitdm.ac.in",
    phone: "+91-XXXXXXXXXX",
    office: "Faculty Block, Room 102",
    education: [
      { degree: "Ph.D", university: "IIT Bombay", year: "2017" },
      { degree: "M.Tech", university: "IIT Kharagpur", year: "2011" },
      { degree: "B.Tech", university: "JNTU Hyderabad", year: "2009" },
    ],
    publications: 18,
    projects: 6,
    students: 8,
    courses: ["Computer Architecture", "Digital Systems Design", "Machine Learning"],
    socialLinks: {
      linkedin: "https://linkedin.com/in/",
      github: "https://github.com/",
      website: "https://example.com/",
    },
    interestIcons: [
      { icon: "Cpu", component: Cpu },
      { icon: "Database", component: Database },
      { icon: "BrainCircuit", component: BrainCircuit },
      { icon: "ImageIcon", component: ImageIcon },
      { icon: "Network", component: Network },
    ],
  },
  {
    id: 3,
    name: "Dr. Jagadeesh Kakarla",
    position: "Assistant Professor",
    image: "/placeholder.svg?height=300&width=300",
    interests: ["Wireless Sensor Networks", "Adhoc Networks", "Internet of Things", "Medical Image processing"],
    email: "jagadeesh@iiitdm.ac.in",
    phone: "+91-XXXXXXXXXX",
    office: "Faculty Block, Room 103",
    education: [
      { degree: "Ph.D", university: "IIT Delhi", year: "2016" },
      { degree: "M.Tech", university: "NIT Warangal", year: "2010" },
      { degree: "B.Tech", university: "Andhra University", year: "2008" },
    ],
    publications: 15,
    projects: 5,
    students: 6,
    courses: ["Wireless Networks", "IoT Systems", "Network Security"],
    socialLinks: {
      linkedin: "https://linkedin.com/in/",
      github: "https://github.com/",
      website: "https://example.com/",
    },
    interestIcons: [
      { icon: "Wifi", component: Wifi },
      { icon: "Network", component: Network },
      { icon: "Cpu", component: Cpu },
      { icon: "ImageIcon", component: ImageIcon },
    ],
  },
  {
    id: 4,
    name: "Dr. Jaishree Mayank",
    position: "Assistant Professor",
    image: "/placeholder.svg?height=300&width=300",
    interests: [
      "Scheduling Strategies in Real-time/ Cyber Physical Systems",
      "AI Algorithms for Smart Grids and Electric Vehicle Problems/Drones Problems",
    ],
    email: "jaishree@iiitdm.ac.in",
    phone: "+91-XXXXXXXXXX",
    office: "Faculty Block, Room 104",
    education: [
      { degree: "Ph.D", university: "IIT Madras", year: "2017" },
      { degree: "M.Tech", university: "IIT Roorkee", year: "2011" },
      { degree: "B.Tech", university: "NIT Jaipur", year: "2009" },
    ],
    publications: 14,
    projects: 7,
    students: 4,
    courses: ["Real-time Systems", "AI for Cyber-Physical Systems", "Smart Grid Technologies"],
    socialLinks: {
      linkedin: "https://linkedin.com/in/",
      github: "https://github.com/",
      website: "https://example.com/",
    },
    interestIcons: [
      { icon: "Calendar", component: Calendar },
      { icon: "BrainCircuit", component: BrainCircuit },
      { icon: "Zap", component: Zap },
    ],
  },
  {
    id: 5,
    name: "Dr. Kannadasan K",
    position: "Assistant Professor",
    image: "/placeholder.svg?height=300&width=300",
    interests: ["Brain-Computer Interface", "EEG Signal Processing", "Affective Computing", "Machine Learning"],
    email: "kannadasan@iiitdm.ac.in",
    phone: "+91-XXXXXXXXXX",
    office: "Faculty Block, Room 105",
    education: [
      { degree: "Ph.D", university: "IIT Madras", year: "2018" },
      { degree: "M.Tech", university: "Anna University", year: "2012" },
      { degree: "B.E", university: "Anna University", year: "2010" },
    ],
    publications: 16,
    projects: 5,
    students: 7,
    courses: ["Brain-Computer Interfaces", "Signal Processing", "Machine Learning for Healthcare"],
    socialLinks: {
      linkedin: "https://linkedin.com/in/",
      github: "https://github.com/",
      website: "https://example.com/",
    },
    interestIcons: [
      { icon: "BrainCircuit", component: BrainCircuit },
      { icon: "LineChart", component: LineChart },
      { icon: "User", component: User },
      { icon: "Database", component: Database },
    ],
  },
  {
    id: 6,
    name: "Dr. Krishnakumar Gnanambikai",
    position: "Assistant Professor",
    image: "/placeholder.svg?height=300&width=300",
    interests: ["Micro-architecture Security", "Web Security", "Network Security", "Applications of AI in security"],
    email: "krishnakumar@iiitdm.ac.in",
    phone: "+91-XXXXXXXXXX",
    office: "Faculty Block, Room 106",
    education: [
      { degree: "Ph.D", university: "IISc Bangalore", year: "2016" },
      { degree: "M.Tech", university: "NIT Surathkal", year: "2010" },
      { degree: "B.Tech", university: "Anna University", year: "2008" },
    ],
    publications: 20,
    projects: 8,
    students: 9,
    courses: ["Computer Security", "Network Security", "AI for Cybersecurity"],
    socialLinks: {
      linkedin: "https://linkedin.com/in/",
      github: "https://github.com/",
      website: "https://example.com/",
    },
    interestIcons: [
      { icon: "Cpu", component: Cpu },
      { icon: "Lock", component: Lock },
      { icon: "Network", component: Network },
      { icon: "BrainCircuit", component: BrainCircuit },
    ],
  },
  {
    id: 7,
    name: "Prof. Masilamani V",
    position: "Professor",
    image: "/placeholder.svg?height=300&width=300",
    interests: [
      "Image Processing & Computer Vision",
      "Machine Learning",
      "Algorithms & Data Structure",
      "Theory of Computing",
    ],
    email: "masilamani@iiitdm.ac.in",
    phone: "+91-XXXXXXXXXX",
    office: "Faculty Block, Room 107",
    education: [
      { degree: "Ph.D", university: "IIT Delhi", year: "2010" },
      { degree: "M.Tech", university: "IIT Bombay", year: "2004" },
      { degree: "B.Tech", university: "NIT Trichy", year: "2002" },
    ],
    publications: 45,
    projects: 12,
    students: 15,
    courses: ["Computer Vision", "Advanced Algorithms", "Machine Learning"],
    socialLinks: {
      linkedin: "https://linkedin.com/in/",
      github: "https://github.com/",
      website: "https://example.com/",
    },
    interestIcons: [
      { icon: "ImageIcon", component: ImageIcon },
      { icon: "Eye", component: Eye },
      { icon: "BrainCircuit", component: BrainCircuit },
      { icon: "FileText", component: FileText },
      { icon: "BookMarked", component: BookMarked },
    ],
  },
  {
    id: 8,
    name: "Dr. Noor Mahammad S K",
    position: "Associate Professor",
    image: "/placeholder.svg?height=300&width=300",
    interests: [
      "Software for VLSI Design",
      "Evolvable Hardware",
      "Reconfigurable Computing",
      "Network System Design",
      "Software Defined Radio",
      "High Performance VLSI Architectures for Digital Signal Processing",
      "Packet Processing Architectures and Algorithms",
      "Computer Architecture",
    ],
    email: "noor@iiitdm.ac.in",
    phone: "+91-XXXXXXXXXX",
    office: "Faculty Block, Room 108",
    education: [
      { degree: "Ph.D", university: "IIT Kharagpur", year: "2009" },
      { degree: "M.Tech", university: "IIT Kharagpur", year: "2003" },
      { degree: "B.Tech", university: "JNTU Hyderabad", year: "2001" },
    ],
    publications: 38,
    projects: 14,
    students: 12,
    courses: ["VLSI Design", "Computer Architecture", "Reconfigurable Computing"],
    socialLinks: {
      linkedin: "https://linkedin.com/in/",
      github: "https://github.com/",
      website: "https://example.com/",
    },
    interestIcons: [
      { icon: "Cpu", component: Cpu },
      { icon: "FileText", component: FileText },
      { icon: "Network", component: Network },
    ],
  },
  {
    id: 9,
    name: "Dr. Pandiri Venkatesh",
    position: "Assistant Professor",
    image: "/placeholder.svg?height=300&width=300",
    interests: [
      "Combinatorial Optimization",
      "Reinforcement learning for optimization",
      "Soft computing",
      "Heuristics",
      "Metaheuristics",
      "Swarm Intelligence",
      "Multi-objective Optimization",
    ],
    email: "venkatesh@iiitdm.ac.in",
    phone: "+91-XXXXXXXXXX",
    office: "Faculty Block, Room 109",
    education: [
      { degree: "Ph.D", university: "IIT Hyderabad", year: "2017" },
      { degree: "M.Tech", university: "NIT Warangal", year: "2011" },
      { degree: "B.Tech", university: "JNTU Kakinada", year: "2009" },
    ],
    publications: 22,
    projects: 6,
    students: 8,
    courses: ["Optimization Techniques", "Reinforcement Learning", "Soft Computing"],
    socialLinks: {
      linkedin: "https://linkedin.com/in/",
      github: "https://github.com/",
      website: "https://example.com/",
    },
    interestIcons: [
      { icon: "BrainCircuit", component: BrainCircuit },
      { icon: "LineChart", component: LineChart },
      { icon: "Database", component: Database },
    ],
  },
  {
    id: 10,
    name: "Dr. Preeth R",
    position: "Assistant Professor",
    image: "/placeholder.svg?height=300&width=300",
    interests: ["IoT and Cloud Computing", "Machine Learning", "Computer Vision", "Computer Networks", "Data Science"],
    email: "preeth@iiitdm.ac.in",
    phone: "+91-XXXXXXXXXX",
    office: "Faculty Block, Room 110",
    education: [
      { degree: "Ph.D", university: "IIT Madras", year: "2018" },
      { degree: "M.Tech", university: "NIT Trichy", year: "2012" },
      { degree: "B.Tech", university: "Anna University", year: "2010" },
    ],
    publications: 17,
    projects: 5,
    students: 6,
    courses: ["Cloud Computing", "IoT Systems", "Computer Vision"],
    socialLinks: {
      linkedin: "https://linkedin.com/in/",
      github: "https://github.com/",
      website: "https://example.com/",
    },
    interestIcons: [
      { icon: "Cloud", component: Cloud },
      { icon: "Wifi", component: Wifi },
      { icon: "BrainCircuit", component: BrainCircuit },
      { icon: "Eye", component: Eye },
      { icon: "Network", component: Network },
      { icon: "Database", component: Database },
    ],
  },
  {
    id: 11,
    name: "Dr. Rahul Raman",
    position: "Assistant Professor",
    image: "/placeholder.svg?height=300&width=300",
    interests: [
      "Computer Vision",
      "Image Processing",
      "Machine Learning",
      "Biometrics",
      "Visual Surveillance",
      "Aesthetics",
    ],
    email: "rahul@iiitdm.ac.in",
    phone: "+91-XXXXXXXXXX",
    office: "Faculty Block, Room 111",
    education: [
      { degree: "Ph.D", university: "IIT Kanpur", year: "2017" },
      { degree: "M.Tech", university: "IIT Roorkee", year: "2011" },
      { degree: "B.Tech", university: "NIT Calicut", year: "2009" },
    ],
    publications: 19,
    projects: 7,
    students: 5,
    courses: ["Computer Vision", "Image Processing", "Biometric Systems"],
    socialLinks: {
      linkedin: "https://linkedin.com/in/",
      github: "https://github.com/",
      website: "https://example.com/",
    },
    interestIcons: [
      { icon: "Eye", component: Eye },
      { icon: "ImageIcon", component: ImageIcon },
      { icon: "BrainCircuit", component: BrainCircuit },
      { icon: "Fingerprint", component: Fingerprint },
    ],
  },
  {
    id: 12,
    name: "Dr. Sadagopan N",
    position: "Associate Professor",
    image: "/placeholder.svg?height=300&width=300",
    interests: [
      "Graph theory & Combinatorics",
      "Data Structures & Algorithms",
      "Computer Networks",
      "Database Systems",
      "Graph Library Generation Package",
    ],
    email: "sadagopan@iiitdm.ac.in",
    phone: "+91-XXXXXXXXXX",
    office: "Faculty Block, Room 112",
    education: [
      { degree: "Ph.D", university: "IIT Madras", year: "2005" },
      { degree: "M.Tech", university: "IIT Bombay", year: "1999" },
      { degree: "B.Tech", university: "Bharathidasan University", year: "1997" },
    ],
    publications: 42,
    projects: 15,
    students: 18,
    courses: ["Graph Theory", "Advanced Algorithms", "Database Systems"],
    socialLinks: {
      linkedin: "https://linkedin.com/in/",
      github: "https://github.com/",
      website: "https://example.com/",
    },
    interestIcons: [
      { icon: "Network", component: Network },
      { icon: "FileText", component: FileText },
      { icon: "Database", component: Database },
    ],
  },
  {
    id: 13,
    name: "Dr. Sanjeet Kumar Nayak",
    position: "Assistant Professor",
    image: "/placeholder.svg?height=300&width=300",
    interests: [
      "IoT and Cloud Computing",
      "Applied Cryptography",
      "Fog and Edge Computing",
      "Unmanned Aerial Vehicle (UAV)",
      "Blockchain Technology",
    ],
    email: "sanjeet@iiitdm.ac.in",
    phone: "+91-XXXXXXXXXX",
    office: "Faculty Block, Room 113",
    education: [
      { degree: "Ph.D", university: "IIT Kharagpur", year: "2018" },
      { degree: "M.Tech", university: "NIT Rourkela", year: "2012" },
      { degree: "B.Tech", university: "BPUT Odisha", year: "2010" },
    ],
    publications: 16,
    projects: 6,
    students: 7,
    courses: ["Cloud Computing", "Cryptography", "Blockchain Technology"],
    socialLinks: {
      linkedin: "https://linkedin.com/in/",
      github: "https://github.com/",
      website: "https://example.com/",
    },
    interestIcons: [
      { icon: "Cloud", component: Cloud },
      { icon: "Lock", component: Lock },
      { icon: "Wifi", component: Wifi },
    ],
  },
  {
    id: 14,
    name: "Dr. Santhanam Raghavan",
    position: "Assistant Professor",
    image: "/placeholder.svg?height=300&width=300",
    interests: ["Cloud Computing", "Membrane Computing", "Machine Learning"],
    email: "santhanam@iiitdm.ac.in",
    phone: "+91-XXXXXXXXXX",
    office: "Faculty Block, Room 114",
    education: [
      { degree: "Ph.D", university: "IIT Madras", year: "2016" },
      { degree: "M.Tech", university: "Anna University", year: "2010" },
      { degree: "B.E", university: "Anna University", year: "2008" },
    ],
    publications: 14,
    projects: 4,
    students: 5,
    courses: ["Cloud Computing", "Distributed Systems", "Machine Learning"],
    socialLinks: {
      linkedin: "https://linkedin.com/in/",
      github: "https://github.com/",
      website: "https://example.com/",
    },
    interestIcons: [
      { icon: "Cloud", component: Cloud },
      { icon: "Database", component: Database },
      { icon: "BrainCircuit", component: BrainCircuit },
    ],
  },
  {
    id: 15,
    name: "Prof. Sivaselvan B",
    position: "Professor and HOD",
    image: "/placeholder.svg?height=300&width=300",
    interests: [
      "Knowledge & Data Engineering",
      "Data Analytics",
      "Human Computer Interaction",
      "Evolutionary Computation Strategies",
    ],
    email: "sivaselvan@iiitdm.ac.in",
    phone: "+91-XXXXXXXXXX",
    office: "Faculty Block, Room 115",
    education: [
      { degree: "Ph.D", university: "IIT Madras", year: "2008" },
      { degree: "M.Tech", university: "IIT Delhi", year: "2002" },
      { degree: "B.Tech", university: "Madras University", year: "2000" },
    ],
    publications: 55,
    projects: 18,
    students: 22,
    courses: ["Data Engineering", "Human-Computer Interaction", "Evolutionary Computing"],
    socialLinks: {
      linkedin: "https://linkedin.com/in/",
      github: "https://github.com/",
      website: "https://example.com/",
    },
    interestIcons: [
      { icon: "Database", component: Database },
      { icon: "LineChart", component: LineChart },
      { icon: "User", component: User },
      { icon: "BrainCircuit", component: BrainCircuit },
    ],
  },
  {
    id: 16,
    name: "Dr. Vijayakumar S",
    position: "Assistant Professor",
    image: "/placeholder.svg?height=300&width=300",
    interests: ["Artificial Intelligence", "Machine Learning", "Natural Language Processing"],
    email: "vijayakumar@iiitdm.ac.in",
    phone: "+91-XXXXXXXXXX",
    office: "Faculty Block, Room 116",
    education: [
      { degree: "Ph.D", university: "IIT Madras", year: "2017" },
      { degree: "M.Tech", university: "NIT Trichy", year: "2011" },
      { degree: "B.Tech", university: "Anna University", year: "2009" },
    ],
    publications: 18,
    projects: 6,
    students: 8,
    courses: ["Artificial Intelligence", "Natural Language Processing", "Deep Learning"],
    socialLinks: {
      linkedin: "https://linkedin.com/in/",
      github: "https://github.com/",
      website: "https://example.com/",
    },
    interestIcons: [
      { icon: "BrainCircuit", component: BrainCircuit },
      { icon: "Database", component: Database },
    ],
  },
  {
    id: 17,
    name: "Dr. Umarani Jayaraman",
    position: "Assistant Professor",
    image: "/placeholder.svg?height=300&width=300",
    interests: [
      "Biometrics",
      "Pattern Recognition",
      "Deep Learning",
      "Digital Image Processing",
      "Human Computer Interaction",
    ],
    email: "umarani@iiitdm.ac.in",
    phone: "+91-XXXXXXXXXX",
    office: "Faculty Block, Room 117",
    education: [
      { degree: "Ph.D", university: "IIT Delhi", year: "2015" },
      { degree: "M.Tech", university: "IIT Kanpur", year: "2009" },
      { degree: "B.Tech", university: "Anna University", year: "2007" },
    ],
    publications: 24,
    projects: 9,
    students: 11,
    courses: ["Biometric Systems", "Pattern Recognition", "Image Processing"],
    socialLinks: {
      linkedin: "https://linkedin.com/in/",
      github: "https://github.com/",
      website: "https://example.com/",
    },
    interestIcons: [
      { icon: "Fingerprint", component: Fingerprint },
      { icon: "BrainCircuit", component: BrainCircuit },
      { icon: "ImageIcon", component: ImageIcon },
      { icon: "User", component: User },
    ],
  },
]

// Research areas for filtering
export const researchAreas = [
  { name: "All Areas", value: "all" },
  { name: "Machine Learning & AI", value: "Machine Learning", icon: BrainCircuit },
  { name: "Computer Vision & Image Processing", value: "Image Processing", icon: Eye },
  { name: "Networks & IoT", value: "Networks", icon: Network },
  { name: "Security & Cryptography", value: "Security", icon: Lock },
  { name: "Data Science & Analytics", value: "Data", icon: Database },
  { name: "Computer Architecture", value: "Computer Architecture", icon: Cpu },
  { name: "Algorithms & Theory", value: "Algorithms", icon: FileText },
  { name: "Human-Computer Interaction", value: "Human Computer Interaction", icon: User },
  { name: "Cloud Computing", value: "Cloud Computing", icon: Cloud },
]

// Faculty positions for filtering
export const positions = [
  { name: "All Positions", value: "all" },
  { name: "Professor", value: "Professor" },
  { name: "Associate Professor", value: "Associate Professor" },
  { name: "Assistant Professor", value: "Assistant Professor" },
]

// Department stats
export const departmentStats = {
  total: facultyData.length,
  professors: facultyData.filter(
    (f) => f.position.includes("Professor") && !f.position.includes("Associate") && !f.position.includes("Assistant"),
  ).length,
  associateProfessors: facultyData.filter((f) => f.position.includes("Associate")).length,
  assistantProfessors: facultyData.filter((f) => f.position.includes("Assistant")).length,
  totalPublications: facultyData.reduce((sum, faculty) => sum + faculty.publications, 0),
  totalProjects: facultyData.reduce((sum, faculty) => sum + faculty.projects, 0),
  totalStudents: facultyData.reduce((sum, faculty) => sum + faculty.students, 0),
}

// Function to get random color gradient for faculty cards
export const getRandomGradient = (id: number) => {
  const gradients = [
    "from-blue-500 to-blue-600",
    "from-indigo-500 to-indigo-600",
    "from-purple-500 to-purple-600",
    "from-cyan-500 to-cyan-600",
    "from-teal-500 to-teal-600",
    "from-green-500 to-green-600",
    "from-amber-500 to-amber-600",
    "from-rose-500 to-rose-600",
  ]
  return gradients[id % gradients.length]
}

