// Alumni data structured in JSON format
export interface AlumniInterface {
  id: number
  name: string
  graduationYear: number
  currentPosition: string
  image: string
  country: string
  company?: string
  university?: string
}

export const alumniData: AlumniInterface[] = [
  {
    id: 1,
    name: "B. Illambharathi",
    graduationYear: 2013,
    currentPosition: "MS at Columbia, currently at Yahoo Labs",
    image: "/placeholder.svg?height=150&width=150",
    country: "USA",
    company: "Yahoo Labs",
  },
  {
    id: 2,
    name: "R. Niveditha",
    graduationYear: 2013,
    currentPosition: "MS at Georgia Tech, currently at Facebook",
    image: "/placeholder.svg?height=150&width=150",
    country: "USA",
    company: "Facebook",
  },
  {
    id: 3,
    name: "Surabhi Jain",
    graduationYear: 2013,
    currentPosition: "MS at Ohio State, currently at Intel Inc",
    image: "/placeholder.svg?height=150&width=150",
    country: "USA",
    company: "Intel Inc",
  },
  {
    id: 4,
    name: "Suganth Krishna",
    graduationYear: 2013,
    currentPosition: "MS at Univ of California, San Diego",
    image: "/placeholder.svg?height=150&width=150",
    country: "USA",
    university: "UC San Diego",
  },
  {
    id: 5,
    name: "Ramesh Krishnan",
    graduationYear: 2014,
    currentPosition: "Direct Ph.D at Pen State, currently at Boston University",
    image: "/placeholder.svg?height=150&width=150",
    country: "USA",
    university: "Boston University",
  },
  {
    id: 6,
    name: "Anand Vijayaraghavan",
    graduationYear: 2014,
    currentPosition: "MS at North Carolina State University",
    image: "/placeholder.svg?height=150&width=150",
    country: "USA",
    university: "North Carolina State University",
  },
  {
    id: 7,
    name: "Varun Chandra",
    graduationYear: 2014,
    currentPosition: "MS-Ph.D at Arizona State University",
    image: "/placeholder.svg?height=150&width=150",
    country: "USA",
    university: "Arizona State University",
  },
  {
    id: 8,
    name: "Gireesh S",
    graduationYear: 2014,
    currentPosition: "MS at Arizona State University, currently at Amazon",
    image: "/placeholder.svg?height=150&width=150",
    country: "USA",
    company: "Amazon",
  },
  {
    id: 9,
    name: "Sowmya Jain",
    graduationYear: 2014,
    currentPosition: "MS at Univ of California, Irvine, currently at Facebook",
    image: "/placeholder.svg?height=150&width=150",
    country: "USA",
    company: "Facebook",
  },
  {
    id: 10,
    name: "Noone Sowmya",
    graduationYear: 2014,
    currentPosition: "MS at University of Connecticut",
    image: "/placeholder.svg?height=150&width=150",
    country: "USA",
    university: "University of Connecticut",
  },
  {
    id: 11,
    name: "Manogana V",
    graduationYear: 2015,
    currentPosition: "MS at Arizona State University, currently at Yahoo",
    image: "/placeholder.svg?height=150&width=150",
    country: "USA",
    company: "Yahoo",
  },
  {
    id: 12,
    name: "Madhu Illuri",
    graduationYear: 2015,
    currentPosition: "MS at Arizona State University",
    image: "/placeholder.svg?height=150&width=150",
    country: "USA",
    university: "Arizona State University",
  },
  {
    id: 13,
    name: "Siddarth Agarwal",
    graduationYear: 2015,
    currentPosition: "MS at Univ of California, San Diego",
    image: "/placeholder.svg?height=150&width=150",
    country: "USA",
    university: "UC San Diego",
  },
  {
    id: 14,
    name: "Krishna Mohan Reddy",
    graduationYear: 2015,
    currentPosition: "MS at Arizona, currently at Facebook",
    image: "/placeholder.svg?height=150&width=150",
    country: "USA",
    company: "Facebook",
  },
  {
    id: 15,
    name: "Iniyai T",
    graduationYear: 2016,
    currentPosition: "MS at University of Souther California",
    image: "/placeholder.svg?height=150&width=150",
    country: "USA",
    university: "University of Southern California",
  },
  {
    id: 16,
    name: "Harikrishna M",
    graduationYear: 2016,
    currentPosition: "MS at North Carolina State University",
    image: "/placeholder.svg?height=150&width=150",
    country: "USA",
    university: "North Carolina State University",
  },
  {
    id: 17,
    name: "Avinash G",
    graduationYear: 2016,
    currentPosition: "MS at Univ california, Losangles",
    image: "/placeholder.svg?height=150&width=150",
    country: "USA",
    university: "UCLA",
  },
  {
    id: 18,
    name: "Shubham K Singh",
    graduationYear: 2016,
    currentPosition: "MS at International Business, Maastricht University, Netherlands",
    image: "/placeholder.svg?height=150&width=150",
    country: "Netherlands",
    university: "Maastricht University",
  },
  {
    id: 19,
    name: "Hari Krishna",
    graduationYear: 2016,
    currentPosition: "Arizona State University",
    image: "/placeholder.svg?height=150&width=150",
    country: "USA",
    university: "Arizona State University",
  },
  {
    id: 20,
    name: "Sai Hemanth Gantasala",
    graduationYear: 2016,
    currentPosition: "MS at Arizona State University",
    image: "/placeholder.svg?height=150&width=150",
    country: "USA",
    university: "Arizona State University",
  },
  {
    id: 21,
    name: "Neeraj",
    graduationYear: 2017,
    currentPosition: "University of Amsterdam",
    image: "/placeholder.svg?height=150&width=150",
    country: "Netherlands",
    university: "University of Amsterdam",
  },
  {
    id: 22,
    name: "Avinash Ranganathan",
    graduationYear: 2017,
    currentPosition: "EMS European Management School",
    image: "/placeholder.svg?height=150&width=150",
    country: "Europe",
    university: "EMS European Management School",
  },
  {
    id: 23,
    name: "Sai Teja",
    graduationYear: 2017,
    currentPosition: "Masters at Sweden",
    image: "/placeholder.svg?height=150&width=150",
    country: "Sweden",
    university: "Sweden University",
  },
  {
    id: 24,
    name: "Ashiq",
    graduationYear: 2017,
    currentPosition: "Cambridge",
    image: "/placeholder.svg?height=150&width=150",
    country: "UK",
    university: "Cambridge University",
  },
  {
    id: 25,
    name: "Dhayalan",
    graduationYear: 2017,
    currentPosition: "University of Amsterdam",
    image: "/placeholder.svg?height=150&width=150",
    country: "Netherlands",
    university: "University of Amsterdam",
  },
  {
    id: 26,
    name: "Shantanu K",
    graduationYear: 2017,
    currentPosition: "University of Colorado Boulder",
    image: "/placeholder.svg?height=150&width=150",
    country: "USA",
    university: "University of Colorado Boulder",
  },
  {
    id: 27,
    name: "Seshu",
    graduationYear: 2017,
    currentPosition: "UT Dallas",
    image: "/placeholder.svg?height=150&width=150",
    country: "USA",
    university: "UT Dallas",
  },
  {
    id: 28,
    name: "Seshuram S",
    graduationYear: 2017,
    currentPosition: "MS at Univ of Texas, Dallas",
    image: "/placeholder.svg?height=150&width=150",
    country: "USA",
    university: "UT Dallas",
  },
  {
    id: 29,
    name: "Vijay Sri L",
    graduationYear: 2017,
    currentPosition: "MS at Georgia Tech",
    image: "/placeholder.svg?height=150&width=150",
    country: "USA",
    university: "Georgia Tech",
  },
  {
    id: 30,
    name: "Dileep Vemula",
    graduationYear: 2018,
    currentPosition: "MS at Australian National University",
    image: "/placeholder.svg?height=150&width=150",
    country: "Australia",
    university: "Australian National University",
  },
  {
    id: 31,
    name: "Dakshaja Uppalapati",
    graduationYear: 2018,
    currentPosition: "Emertxe",
    image: "/placeholder.svg?height=150&width=150",
    country: "International",
    company: "Emertxe",
  },
  {
    id: 32,
    name: "Nara Ashok Chakravarthy",
    graduationYear: 2018,
    currentPosition: "MS at Australian National University",
    image: "/placeholder.svg?height=150&width=150",
    country: "Australia",
    university: "Australian National University",
  },
  {
    id: 33,
    name: "Edwin Murari",
    graduationYear: 2018,
    currentPosition: "MS at University of Melbourne",
    image: "/placeholder.svg?height=150&width=150",
    country: "Australia",
    university: "University of Melbourne",
  },
  {
    id: 34,
    name: "Anuhya K",
    graduationYear: 2018,
    currentPosition: "MS at UNCC",
    image: "/placeholder.svg?height=150&width=150",
    country: "USA",
    university: "UNCC",
  },
  {
    id: 35,
    name: "Vignesh Sairaj",
    graduationYear: 2018,
    currentPosition: "MS at University of Souther California, currently at Apple Inc",
    image: "/placeholder.svg?height=150&width=150",
    country: "USA",
    company: "Apple Inc",
  },
  {
    id: 36,
    name: "P Kowsika",
    graduationYear: 2019,
    currentPosition: "Ohio State, MS",
    image: "/placeholder.svg?height=150&width=150",
    country: "USA",
    university: "Ohio State University",
  },
  {
    id: 37,
    name: "Shiv Vidhyut",
    graduationYear: 2019,
    currentPosition: "Columbia University, Newyork, MS",
    image: "/placeholder.svg?height=150&width=150",
    country: "USA",
    university: "Columbia University",
  },
  {
    id: 38,
    name: "Shreya Suresh",
    graduationYear: 2019,
    currentPosition: "University of Maryland, MS",
    image: "/placeholder.svg?height=150&width=150",
    country: "USA",
    university: "University of Maryland",
  },
  {
    id: 39,
    name: "Aishwarya R",
    graduationYear: 2019,
    currentPosition: "University of Massachusetts, MS",
    image: "/placeholder.svg?height=150&width=150",
    country: "USA",
    university: "University of Massachusetts",
  },
  {
    id: 40,
    name: "KS Ranjth Raj",
    graduationYear: 2019,
    currentPosition: "Australian National University, MS",
    image: "/placeholder.svg?height=150&width=150",
    country: "Australia",
    university: "Australian National University",
  },
  {
    id: 41,
    name: "Prashanth Reddy",
    graduationYear: 2019,
    currentPosition: "University of Davis, MS",
    image: "/placeholder.svg?height=150&width=150",
    country: "USA",
    university: "University of Davis",
  },
]

// Get unique graduation years for filtering
export const graduationYears = [...new Set(alumniData.map((alumni) => alumni.graduationYear))].sort()

// Get unique countries for filtering
export const countries = [...new Set(alumniData.map((alumni) => alumni.country))].sort()

// Group alumni by graduation year for statistics
export const alumniByYear = graduationYears.map((year) => ({
  year,
  count: alumniData.filter((alumni) => alumni.graduationYear === year).length,
}))

// Group alumni by country for statistics
export const alumniByCountry = countries
  .map((country) => ({
    country,
    count: alumniData.filter((alumni) => alumni.country === country).length,
  }))
  .sort((a, b) => b.count - a.count)

