// Project data
export const projects = [
  {
    id: 1,
    title: "Machine Learning Algorithms for Security Applications & Image Processing",
    type: "faculty",
    pi: "Dr. V Masilamani",
    copi: [],
    sponsor: "Forensics Intelligence Surveillance and Security Technologies Pvt. Ltd. Chennai",
    duration: "Two Years",
    value: "6 Lakhs",
    status: "Completed",
    image: "/placeholder.svg?height=400&width=600",
    description:
      "This project focuses on developing advanced machine learning algorithms for security applications and image processing. The research aims to enhance surveillance systems with intelligent features for threat detection and image analysis.",
    outcomes: [
      "Developed novel ML algorithms for security surveillance",
      "Created image processing techniques for forensic analysis",
      "Published 2 research papers in international journals",
      "Filed 1 patent for the developed technology",
    ],
    technologies: ["Machine Learning", "Computer Vision", "Image Processing", "Security Systems"],
  },
  {
    id: 2,
    title: "People Counter for Bus",
    type: "faculty",
    pi: "Dr. V Masilamani",
    copi: ["Prof. Banshidhar Majhi"],
    sponsor: "Vamo Systems Private Ltd. Chennai",
    duration: "1 year",
    value: "2 Lakhs",
    status: "Completed",
    image: "/placeholder.svg?height=400&width=600",
    description:
      "This project involves developing an automated system to count passengers entering and exiting buses. The technology uses computer vision and sensor fusion to provide accurate passenger counts for public transportation management.",
    outcomes: [
      "Developed a prototype with 95% counting accuracy",
      "Implemented in 5 test buses for field trials",
      "Created a dashboard for real-time monitoring",
      "Reduced manual counting errors by 85%",
    ],
    technologies: ["Computer Vision", "IoT", "Embedded Systems", "Data Analytics"],
  },
  {
    id: 3,
    title: "'MediVo' - An online portal for e-consultation customized to dentists",
    type: "student",
    studentMembers: ["S Lokesh Kumar", "R Neeraj", "Shubham Kumar Gandhi", "Adarsh Srivatasava"],
    studentBatch: "B.Tech COE - Class of 2013-17",
    facultyAdviser: "Dr. N Sadagopan",
    status: "Completed and Transferred",
    company: "vexo.org",
    image: "/placeholder.svg?height=400&width=600",
    description:
      "MediVo is an online portal designed specifically for dental e-consultations. The platform enables dentists to conduct virtual consultations, manage patient records, and schedule appointments efficiently.",
    outcomes: [
      "Developed a fully functional UI meeting dentist specifications",
      "Created secure patient data management system",
      "Implemented video consultation features",
      "Transferred to vexo.org for further enhancement",
    ],
    technologies: ["Web Development", "Healthcare IT", "UI/UX Design", "Telemedicine"],
  },
  {
    id: 4,
    title: "Object Reconstruction from a stream of projections of CT scan images",
    type: "student",
    studentMembers: ["M Aishwarya"],
    studentBatch: "B.Tech 2014-18",
    facultyAdviser: "Dr. N Sadagopan",
    company: "LUCID Technologies Ltd, Chennai",
    status: "Completed",
    image: "/placeholder.svg?height=400&width=600",
    description:
      "This project focuses on developing algorithms for reconstructing 3D objects from CT scan image projections. The technology enables more accurate medical diagnostics and visualization of internal structures.",
    outcomes: [
      "Developed reconstruction algorithms with high accuracy",
      "Reduced processing time by 40% compared to existing methods",
      "Created visualization tools for medical professionals",
      "Implemented in LUCID's medical imaging software",
    ],
    technologies: ["Medical Imaging", "Computer Vision", "3D Reconstruction", "Algorithm Design"],
  },
  {
    id: 5,
    title: "Open Source Web Server Design to mimic AKAMAI features",
    type: "student",
    studentMembers: ["P Lalitha"],
    studentBatch: "B.Tech 2014-18",
    facultyAdviser: "Dr. N Sadagopan",
    company: "Start Smart Labs, Chennai",
    status: "Completed",
    image: "/placeholder.svg?height=400&width=600",
    description:
      "This project involves designing an open-source web server that replicates key features of AKAMAI's content delivery network. The server aims to provide efficient content delivery and caching capabilities.",
    outcomes: [
      "Developed an open-source web server with CDN capabilities",
      "Implemented caching mechanisms for improved performance",
      "Created load balancing features for high availability",
      "Achieved 30% faster content delivery in testing",
    ],
    technologies: [
      "Web Server Architecture",
      "Content Delivery Networks",
      "Distributed Systems",
      "Open Source Development",
    ],
  },
]

